version: 2

jobs:
  build-3.7: &build
    parallelism: 1
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7.3-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'venv'
      - restore_cache:
          keys:
            - 'tox-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}'

      - run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -U tox

      - save_cache:
          key: 'venv'
          paths:
            - .venv

      - run: |
          source .venv/bin/activate
          tox

      - save_cache:
          key: 'tox-{{ checksum "tox.ini" }}-{{ checksum "setup.py" }}'
          paths:
            - .tox

      - store_test_results:
          path: .tox/py37/artifacts/

  build-3.8:
    <<: *build
    docker:
      - image: circleci/python:3.8.0-node-browsers
